#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Gradle template within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true   ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
#     and any embedded shellness will be escaped.
#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
#     treated as '${Hostname}' itself on the command line.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments).
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"

# Set a couple of environment variables that are used by Gradle, if they are not set.
#
# GPR_SYS_PROPS can be used to pass system properties to the Gradle JVM, i.e.
# the JVM that is running Gradle. The system properties are applied before any
# build scripts are executed.
#
# So, to pass a system property to the wrapper, either set the environment
# variable, e.g. GPR_SYS_PROPS="-Dprop=value" or add it to gradle.properties.
#
# Not all system properties can be set via this mechanism. Some system properties
# are used by the JVM to configure the JVM itself. These system properties must
# be passed directly to the JVM as command line arguments.

if [ -z "$GPR_SYS_PROPS" ]; then
    GPR_SYS_PROPS=""
fi

#############################################################################
#
# Helper functions

# The next section contains logic for locating the gradle-wrapper.jar, which is non-trivial.
#
# The wrapper is located by searching the file system relative to the location of this script.
#
# The following locations are checked, in order:
#
# 1. $APP_HOME/gradle/wrapper/gradle-wrapper.jar
#
# 2. $APP_HOME/gradle-wrapper.jar
#
# 3. A jar file found using the zero-length-path search pattern.
#    This search pattern will find the first gradle-wrapper.jar in the current directory,
#    or in any parent directory. This is the preferred location for the wrapper jar,
#    and the location that is used by the Gradle project by default.
#
# If the wrapper jar cannot be located, the script will die.

# The die function is used to exit the script with an error message.
die () {
    echo "$*"
    exit 1
} >&2

# The find_upwards function is used to find a file by searching upwards from the
# current directory.

find_upwards () {
    (
    while [ ! -e "$1" ]
    do
        if [ "$PWD" = "/" ]; then
            break
        fi
        cd ..
    done
    if [ -e "$1" ]; then
        pwd
    fi
    )
}

# The follow_links function is used to resolve any symbolic links in a path.
follow_links() {
    local file="$1"
    while [ -h "$file" ]; do
        local link="$(readlink "$file")"
        if [ -z "$link" ]; then
            break
        fi
        if [ "$(echo "$link" | cut -c1)" = "/" ]; then
            file="$link"
        else
            file="$(dirname "$file")/$link"
        fi
    done
    echo "$file"
}

# End of helper functions
#############################################################################
#
# Locate the gradle-wrapper.jar

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Use the maximum column width for the terminal
# The default is 80, but that may not be wide enough for some of the error messages.
#
# The tput command is used to get the number of columns, but it is not available
# on all systems. If it is not available, we will default to 80.
#
if [ -x /usr/bin/tput ]; then
    COLUMNS=`/usr/bin/tput cols`
fi
if [ -z "$COLUMNS" ] || [ "$COLUMNS" -lt 80 ]; then
    COLUMNS=80
fi

# The sed command is used to wrap the error messages to the width of the terminal.
#
# The first sed command will replace all occurrences of a space with a newline,
# and then the second sed command will add a newline every N characters, where N
# is the number of columns.
#
# The fold command is used to wrap the error messages to the width of the terminal.
#
if [ -x /usr/bin/fold ]; then
    WRAPPER_NAME=`echo "$APP_NAME Wrapper" | fold -s -w $COLUMNS`
else
    WRAPPER_NAME=`echo "$APP_NAME Wrapper"`
fi

# The realpath command is used to get the canonical path to the script.
#
# If the realpath command is not available, we will use our own implementation.
#
if [ -x /usr/bin/realpath ]; then
    APP_HOME=`/usr/bin/realpath "$0"`
else
    APP_HOME=`follow_links "$0"`
fi
APP_HOME=`dirname "$APP_HOME"`

# The location of the gradle-wrapper.jar is determined by searching for it in a
# number of locations. The first location that is found is used.
#
if [ -e "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
    WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
elif [ -e "$APP_HOME/gradle-wrapper.jar" ]; then
    WRAPPER_JAR="$APP_HOME/gradle-wrapper.jar"
else
    WRAPPER_JAR_LOCATION=`find_upwards gradle/wrapper/gradle-wrapper.jar`
    if [ -n "$WRAPPER_JAR_LOCATION" ]; then
        WRAPPER_JAR="$WRAPPER_JAR_LOCATION/gradle/wrapper/gradle-wrapper.jar"
    fi
fi

if [ -z "$WRAPPER_JAR" ] || [ ! -f "$WRAPPER_JAR" ]; then
    die "
Error: Could not find or load the $WRAPPER_NAME.
Please check that the file exists and is readable.

Searched in the following locations:

* $APP_HOME/gradle/wrapper/gradle-wrapper.jar
* $APP_HOME/gradle-wrapper.jar
* A jar file found using the zero-length-path search pattern.
"
fi

# End of locating the gradle-wrapper.jar
#############################################################################
#
# Build the command line to execute

# The project specific gradle opts are loaded from a .gradleopts file, if it
# exists. The file is located by searching upwards from the current directory.
#
GRADLE_OPTS_FILE_LOCATION=`find_upwards .gradleopts`
if [ -n "$GRADLE_OPTS_FILE_LOCATION" ]; then
    # The sed command is used to remove any comments from the file.
    # The grep command is used to remove any blank lines from the file.
    #
    # The tr command is used to replace any newlines with spaces.
    # The xargs command is used to trim any leading or trailing whitespace.
    #
    PROJECT_GRADLE_OPTS=`cat "$GRADLE_OPTS_FILE_LOCATION/.gradleopts" | sed 's/#.*//' | grep -v '^$' | tr '\n' ' ' | xargs`
fi

# The gradle opts are built from a number of sources.
#
# The order of precedence is as follows:
#
# 1. The project specific gradle opts.
# 2. The default gradle opts.
# 3. The system properties.
#
GRADLE_OPTS="$PROJECT_GRADLE_OPTS $DEFAULT_GRADLE_OPTS $GPR_SYS_PROPS"

# The classpath is built from the gradle-wrapper.jar.
#
CLASSPATH="$WRAPPER_JAR"

# The command line is built from the java command, the gradle opts, the
# classpath, the main class, and the command line arguments.
#
CMD_LINE_ARGS=
for arg in "$@"
do
    CMD_LINE_ARGS="$CMD_LINE_ARGS \"$arg\""
done

# The eval command is used to execute the command line.
#
# This is required because the command line arguments may contain spaces, and
# we need to preserve them.
#
eval "$JAVACMD" $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

